### PR TITLE
Add default_ccache_name, pkinit_anchors

### PR DESCRIPTION
**Pull request by florianfa**

### CODE REVIEW

**Comment by jyaworski** [comment]
@florianfa can you squash?

@pfmooney I'd _love_ for this to get merged. pkinit_anchors is the one thing stopping me from using this.

**Comment by florianfa** [comment]
Hi pfmooney,

sorry, but what do you mean with "Can you sqash?".

Regards,
Florian

**Comment by jyaworski** [comment]
@florianfa please see:

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by florianfa** [comment]
Hi pfmooney,

I've squashed the commits.

Regards,
Florian

**Comment by pfmooney** [comment]
Merged in 56030dd6e4662b09559fe6a684eaf6f7e56ba37d.

Thanks

**Comment by pfmooney** [comment]
@jyaworski This was released to the forge as v0.0.8.

**Pull request closed without merging**
